### ISSUE TITLE
problem with installing on paraview 5.8

### ISSUE THREAD

**Issue by zeineldin117** [tianyikillua/paraview-meshio#3]
I get this error message when i try to load the plugin to paraivew 5.8
______________________________________________________________________________________________________
Generic Warning: In /home/buildslave/dashboards/buildbot/paraview-pvbinsdash-linux-shared-release_superbuild/build/superbuild/paraview/src/Remoting/ServerManagerPython/vtkPVPythonAlgorithmPlugin.cxx, line 187
Failed to load Python plugin:
Failed to call `paraview.detail.pythonalgorithm.load_plugin`.

Traceback (most recent call last):
  File "/data/openFOAM/ParaView-5.8.0-MPI-Linux-Python3.7-64bit/lib/python3.7/site-packages/paraview/detail/pythonalgorithm.py", line 509, in load_plugin
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/openFOAM/ParaView-5.8.0-MPI-Linux-Python3.7-64bit/plugins/paraview-meshio-master/meshioPlugin.py", line 1, in <module>
    import meshio
ModuleNotFoundError: No module named 'meshio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/openFOAM/ParaView-5.8.0-MPI-Linux-Python3.7-64bit/lib/python3.7/site-packages/paraview/detail/pythonalgorithm.py", line 513, in load_plugin
    module = imp.load_source(modulename, filepath)
  File "/data/openFOAM/ParaView-5.8.0-MPI-Linux-Python3.7-64bit/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/openFOAM/ParaView-5.8.0-MPI-Linux-Python3.7-64bit/plugins/paraview-meshio-master/meshioPlugin.py", line 1, in <module>
    import meshio
ModuleNotFoundError: No module named 'meshio'
ERROR: In /home/buildslave/dashboards/buildbot/paraview-pvbinsdash-linux-shared-release_superbuild/build/superbuild/paraview/src/Remoting/Core/vtkPVPluginLoader.cxx, line 519
vtkPVPluginLoader (0x5bf63f0): /data/openFOAM/ParaView-5.8.0-MPI-Linux-Python3.7-64bit/plugins/paraview-meshio-master/meshioPlugin.py: invalid ELF head

**Comment by tianyikillua** [comment]
Thanks for reporting. Could you please using the [plugin file](https://github.com/nschloe/meshio/blob/master/tools/paraview-meshio-plugin.py) bundled with `meshio`?

By the way you need to first install the `meshio` package. You need to copy it to your ParaView Python directory.
